package main

import (
	"fmt"
	"log"

	"gin-boilerplate/internal/config"
	"gin-boilerplate/internal/database"
	"gin-boilerplate/internal/handler"
	"gin-boilerplate/internal/middleware"
	"gin-boilerplate/internal/repository"
	"gin-boilerplate/internal/service"
	"gin-boilerplate/pkg/utils"

	_ "gin-boilerplate/docs" // This will be generated by swag init

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Gin Boilerplate API
// @version 1.0
// @description API for Fleet Administration Backend.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization

func main() {
	// Load config
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("Failed to load config: %v", err)
	}

	// Connect to database
	db, err := database.NewPostgresDB(cfg)
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	log.Println("✅ Database connected successfully")

	// Set Gin mode
	if cfg.App.Env == "production" {
		gin.SetMode(gin.ReleaseMode)
	}

	// Auto Migrate dimatikan sesuai permintaan user agar tidak mengubah struktur DB

	// Initialize utilities
	jwtUtil := utils.NewJWTUtil(cfg.JWT.Secret, cfg.JWT.ExpiryHours)

	// Initialize layers (Repository → Service → Handler)
	userRepo := repository.NewUserRepository(db)
	menuRepo := repository.NewMenuRepository(db)
	roleRepo := repository.NewRoleRepository(db)
	accessRepo := repository.NewAccessRepository(db)
	dermagaRepo := repository.NewDermagaRepository(db)

	authService := service.NewAuthService(userRepo, jwtUtil)
	userService := service.NewUserService(userRepo)
	accessService := service.NewAccessService(accessRepo, menuRepo)
	menuService := service.NewMenuService(menuRepo, accessService)
	roleService := service.NewRoleService(roleRepo, accessService)
	dermagaService := service.NewDermagaService(dermagaRepo)

	authHandler := handler.NewAuthHandler(authService)
	userHandler := handler.NewUserHandler(userService)
	menuHandler := handler.NewMenuHandler(menuService)
	roleHandler := handler.NewRoleHandler(roleService)
	accessHandler := handler.NewAccessHandler(accessService)
	dermagaHandler := handler.NewDermagaHandler(dermagaService)

	// Setup router
	r := gin.New()
	r.Use(gin.Recovery())
	r.Use(middleware.Logger())
	r.Use(middleware.CORS())

	// Health check
	r.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status":  "ok",
			"service": "gin-boilerplate",
		})
	})

	// Swagger documentation
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// API v1 routes
	v1 := r.Group("/api/v1")
	{
		// Auth routes (public)
		auth := v1.Group("/auth")
		{
			auth.POST("/register", authHandler.Register)
			auth.POST("/login", authHandler.Login)
		}

		// Protected routes
		protected := v1.Group("/")
		protected.Use(middleware.AuthMiddleware(jwtUtil))
		{
			// User routes
			users := protected.Group("/users")
			{
				users.GET("/profile", userHandler.GetProfile)
			}

			// Master routes
			master := protected.Group("/master")
			{
				// Menu routes
				menus := master.Group("/menus")
				{
					menus.GET("", menuHandler.GetAllMenus)
					menus.POST("", menuHandler.CreateMenu)
					menus.PUT("/:id", menuHandler.UpdateMenu)
					menus.DELETE("/:id", menuHandler.DeleteMenu)
				}

				// Role routes
				roles := master.Group("/roles")
				{
					roles.GET("", roleHandler.GetAllRoles)
					roles.POST("", roleHandler.CreateRole)
					roles.PUT("/:id", roleHandler.UpdateRole)
					roles.DELETE("/:id", roleHandler.DeleteRole)
					roles.GET("/:id/access", accessHandler.GetRoleAccess)
					roles.POST("/:id/access", accessHandler.UpdateRoleAccess)
				}
			}

			// Dermaga routes
			dermagas := protected.Group("/dermaga")
			{
				dermagas.POST("", dermagaHandler.Create)
				dermagas.GET("", dermagaHandler.FindAll)
				dermagas.GET("/:id", dermagaHandler.FindByID)
				dermagas.PUT("/:id", dermagaHandler.Update)
				dermagas.DELETE("/:id", dermagaHandler.Delete)
			}
		}
	}

	// Start server
	addr := fmt.Sprintf(":%s", cfg.App.Port)
	log.Printf("🚀 Server running on port : %s", addr)
	log.Printf("📋 Environment: %s", cfg.App.Env)

	if err := r.Run(addr); err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
