package main

import (
	"context"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"gin-boilerplate/internal/config"
	"gin-boilerplate/internal/database"
	"gin-boilerplate/internal/handler"
	"gin-boilerplate/internal/middleware"
	"gin-boilerplate/internal/repository"
	"gin-boilerplate/internal/router"
	"gin-boilerplate/internal/service"
	"gin-boilerplate/pkg/utils"

	_ "gin-boilerplate/docs" // This will be generated by swag init

	"github.com/gin-gonic/gin"
)

// @title Gin Boilerplate API
// @version 1.0
// @description API for Fleet Administration Backend.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization

func main() {
	// Load config first to determine logging mode
	cfg, err := config.Load()
	if err != nil {
		// Log to stdout if config fails
		fmt.Printf("Failed to load config: %v\n", err)
		os.Exit(1)
	}

	// Initialize structured logging based on environment
	logLevel := parseLogLevel(cfg.App.LogLevel)
	var logHandler slog.Handler
	
	if cfg.App.Env == "production" {
		logHandler = slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
			Level: logLevel,
		})
	} else {
		logHandler = slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{
			Level: logLevel,
		})
	}

	logger := slog.New(logHandler)
	slog.SetDefault(logger)

	slog.Debug("Logger initialized with level", "level", cfg.App.LogLevel)

	// Connect to database
	db, err := database.NewPostgresDB(cfg)
	if err != nil {
		slog.Error("Failed to connect to database", "error", err)
		os.Exit(1)
	}
	slog.Info("Database connected successfully")

	// Set Gin mode
	if cfg.App.Env == "production" {
		gin.SetMode(gin.ReleaseMode)
	}

	// Auto Migrate dimatikan sesuai permintaan user agar tidak mengubah struktur DB

	// Initialize utilities
	jwtUtil := utils.NewJWTUtil(cfg.JWT.Secret, cfg.JWT.ExpiryHours)

	// Initialize layers (Repository → Service → Handler)
	userRepo := repository.NewUserRepository(db)
	menuRepo := repository.NewMenuRepository(db)
	roleRepo := repository.NewRoleRepository(db)
	accessRepo := repository.NewAccessRepository(db)
	dermagaRepo := repository.NewDermagaRepository(db)

	authService := service.NewAuthService(userRepo, jwtUtil)
	userService := service.NewUserService(userRepo)
	accessService := service.NewAccessService(accessRepo, menuRepo)
	menuService := service.NewMenuService(menuRepo, accessService)
	roleService := service.NewRoleService(roleRepo, accessService)
	dermagaService := service.NewDermagaService(dermagaRepo)

	authHandler := handler.NewAuthHandler(authService)
	userHandler := handler.NewUserHandler(userService)
	menuHandler := handler.NewMenuHandler(menuService)
	roleHandler := handler.NewRoleHandler(roleService)
	accessHandler := handler.NewAccessHandler(accessService)
	dermagaHandler := handler.NewDermagaHandler(dermagaService)

	// Setup router
	r := gin.New()
	r.Use(gin.Recovery())
	r.Use(middleware.Logger())
	r.Use(middleware.CORS())

	// Setup router
	router.SetupRouter(&router.RouterConfig{
		Engine:         r,
		JWTUtil:        jwtUtil,
		AuthHandler:    authHandler,
		UserHandler:    userHandler,
		MenuHandler:    menuHandler,
		RoleHandler:    roleHandler,
		AccessHandler:  accessHandler,
		DermagaHandler: dermagaHandler,
	})

	// Start server
	addr := fmt.Sprintf(":%s", cfg.App.Port)
	srv := &http.Server{
		Addr:    addr,
		Handler: r,
	}

	// Initializing the server in a goroutine so that it won't block the graceful shutdown handling below
	go func() {
		slog.Info("Server running", "port", cfg.App.Port, "env", cfg.App.Env)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			slog.Error("listen", "error", err)
		}
	}()

	// Wait for interrupt signal to gracefully shutdown the server with a timeout of 5 seconds.
	quit := make(chan os.Signal, 1)
	// kill (no param) default send syscall.SIGTERM
	// kill -2 is syscall.SIGINT
	// kill -9 is syscall.SIGKILL but can't be caught, so no need to add it
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	slog.Info("Shutting down server...")

	// The context is used to inform the server it has 5 seconds to finish
	// the request it is currently handling
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := srv.Shutdown(ctx); err != nil {
		slog.Error("Server forced to shutdown", "error", err)
	}

	slog.Info("Server exiting")
}

func parseLogLevel(level string) slog.Level {
	switch level {
	case "VERBOSE", "DEBUG":
		return slog.LevelDebug
	case "INFO":
		return slog.LevelInfo
	case "WARN":
		return slog.LevelWarn
	case "ERROR":
		return slog.LevelError
	default:
		return slog.LevelInfo
	}
}
